<?php

namespace ContainerVC4mqih;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1SbUjbhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1SbUjbh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1SbUjbh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lignedecommande' => ['privates', '.errored..service_locator.1SbUjbh.App\\Entity\\Lignedecommande', NULL, 'Cannot autowire service ".service_locator.1SbUjbh": it needs an instance of "App\\Entity\\Lignedecommande" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'lignedecommande' => 'App\\Entity\\Lignedecommande',
        ]);
    }
}
