<?php

namespace ContainerVC4mqih;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G7GPtyfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G7GPtyf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G7GPtyf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lignedecommande' => ['privates', '.errored..service_locator.G7GPtyf.App\\Entity\\Lignedecommande', NULL, 'Cannot autowire service ".service_locator.G7GPtyf": it needs an instance of "App\\Entity\\Lignedecommande" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lignedecommande' => 'App\\Entity\\Lignedecommande',
        ]);
    }
}
