<?php

namespace ContainerVC4mqih;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G7lkXRIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g7lkXRI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g7lkXRI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'flashy' => ['services', 'mercuryseries_flashy.flashy_notifier', 'getMercuryseriesFlashy_FlashyNotifierService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'paymentService' => ['privates', 'App\\Service\\PaymentService', 'getPaymentServiceService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'entityManager' => '?',
            'flashy' => '?',
            'mailer' => '?',
            'paymentService' => 'App\\Service\\PaymentService',
            'security' => '?',
        ]);
    }
}
