<?php

namespace ContainerVC4mqih;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T6SdwyjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t6Sdwyj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t6Sdwyj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.t6Sdwyj.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.t6Sdwyj": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'twig' => ['privates', 'twig', 'getTwigService', false],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'twig' => '?',
        ]);
    }
}
