<?php

namespace ContainerChs6MEV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YPr_3LRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yPr.3LR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yPr.3LR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'materiaux' => ['privates', '.errored..service_locator.yPr.3LR.App\\Entity\\Materiaux', NULL, 'Cannot autowire service ".service_locator.yPr.3LR": it needs an instance of "App\\Entity\\Materiaux" but this type has been excluded in "config/services.yaml".'],
        ], [
            'materiaux' => 'App\\Entity\\Materiaux',
        ]);
    }
}
