<?php

namespace ContainerChs6MEV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C6caRhlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c6caRhl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c6caRhl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'atelierenligne' => ['privates', '.errored..service_locator.c6caRhl.App\\Entity\\Atelierenligne', NULL, 'Cannot autowire service ".service_locator.c6caRhl": it needs an instance of "App\\Entity\\Atelierenligne" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'atelierenligne' => 'App\\Entity\\Atelierenligne',
            'entityManager' => '?',
        ]);
    }
}
