<?php

namespace ContainerChs6MEV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KRfs1SlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kRfs1Sl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kRfs1Sl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'inscriptionatelier' => ['privates', '.errored..service_locator.kRfs1Sl.App\\Entity\\Inscriptionatelier', NULL, 'Cannot autowire service ".service_locator.kRfs1Sl": it needs an instance of "App\\Entity\\Inscriptionatelier" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'inscriptionatelier' => 'App\\Entity\\Inscriptionatelier',
        ]);
    }
}
