<?php

namespace ContainerChs6MEV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J6YAmoPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j6YAmoP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j6YAmoP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'atelierenligneRepository' => ['privates', 'App\\Repository\\AtelierenligneRepository', 'getAtelierenligneRepositoryService', true],
        ], [
            'atelierenligneRepository' => 'App\\Repository\\AtelierenligneRepository',
        ]);
    }
}
