<?php

namespace ContainerChs6MEV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMateriauxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2B.aeH_.App\Entity\Materiaux' shared service.
     *
     * @return \App\Entity\Materiaux
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2B.aeH_": it needs an instance of "App\\Entity\\Materiaux" but this type has been excluded in "config/services.yaml".');
    }
}
