<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Atelierenligne extends \App\Entity\Atelierenligne implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null],
        "\0".parent::class."\0".'datecours' => [parent::class, 'datecours', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'duree' => [parent::class, 'duree', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'id_user' => [parent::class, 'id_user', null],
        "\0".parent::class."\0".'inscription' => [parent::class, 'inscription', null],
        "\0".parent::class."\0".'lien' => [parent::class, 'lien', null],
        "\0".parent::class."\0".'niveau_diff' => [parent::class, 'niveau_diff', null],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        'categorie' => [parent::class, 'categorie', null],
        'datecours' => [parent::class, 'datecours', null],
        'description' => [parent::class, 'description', null],
        'duree' => [parent::class, 'duree', null],
        'id' => [parent::class, 'id', null],
        'id_user' => [parent::class, 'id_user', null],
        'inscription' => [parent::class, 'inscription', null],
        'lien' => [parent::class, 'lien', null],
        'niveau_diff' => [parent::class, 'niveau_diff', null],
        'prix' => [parent::class, 'prix', null],
        'titre' => [parent::class, 'titre', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
