<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Promotion extends \App\Entity\Promotion implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'code_coupon' => [parent::class, 'code_coupon', null],
        "\0".parent::class."\0".'end_date' => [parent::class, 'end_date', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'id_produit' => [parent::class, 'id_produit', null],
        "\0".parent::class."\0".'prix_nouv' => [parent::class, 'prix_nouv', null],
        "\0".parent::class."\0".'start_date' => [parent::class, 'start_date', null],
        'code_coupon' => [parent::class, 'code_coupon', null],
        'end_date' => [parent::class, 'end_date', null],
        'id' => [parent::class, 'id', null],
        'id_produit' => [parent::class, 'id_produit', null],
        'prix_nouv' => [parent::class, 'prix_nouv', null],
        'start_date' => [parent::class, 'start_date', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
