<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commande extends \App\Entity\Commande implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse_livraison' => [parent::class, 'adresse_livraison', null],
        "\0".parent::class."\0".'date_commande' => [parent::class, 'date_commande', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'id_lignedecommande' => [parent::class, 'id_lignedecommande', null],
        "\0".parent::class."\0".'id_materiel' => [parent::class, 'id_materiel', null],
        "\0".parent::class."\0".'id_produit' => [parent::class, 'id_produit', null],
        "\0".parent::class."\0".'id_user' => [parent::class, 'id_user', null],
        "\0".parent::class."\0".'montant_total' => [parent::class, 'montant_total', null],
        "\0".parent::class."\0".'paiement' => [parent::class, 'paiement', null],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null],
        'adresse_livraison' => [parent::class, 'adresse_livraison', null],
        'date_commande' => [parent::class, 'date_commande', null],
        'id' => [parent::class, 'id', null],
        'id_lignedecommande' => [parent::class, 'id_lignedecommande', null],
        'id_materiel' => [parent::class, 'id_materiel', null],
        'id_produit' => [parent::class, 'id_produit', null],
        'id_user' => [parent::class, 'id_user', null],
        'montant_total' => [parent::class, 'montant_total', null],
        'paiement' => [parent::class, 'paiement', null],
        'statut' => [parent::class, 'statut', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
