<?php

namespace ContainerQaxzoOb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QCnuuFSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qCnuuFS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qCnuuFS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ProduitController::ajout' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProduitController::liste' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProduitController::modifier' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController::supprimer' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\PromotionController::ajout' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PromotionController::liste' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PromotionController::modifier' => ['privates', '.service_locator.qawdDqK', 'get_ServiceLocator_QawdDqKService', true],
            'App\\Controller\\PromotionController::supprimer' => ['privates', '.service_locator.qawdDqK', 'get_ServiceLocator_QawdDqKService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ProduitController:ajout' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProduitController:liste' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProduitController:modifier' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController:supprimer' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\PromotionController:ajout' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PromotionController:liste' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PromotionController:modifier' => ['privates', '.service_locator.qawdDqK', 'get_ServiceLocator_QawdDqKService', true],
            'App\\Controller\\PromotionController:supprimer' => ['privates', '.service_locator.qawdDqK', 'get_ServiceLocator_QawdDqKService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ProduitController::ajout' => '?',
            'App\\Controller\\ProduitController::liste' => '?',
            'App\\Controller\\ProduitController::modifier' => '?',
            'App\\Controller\\ProduitController::supprimer' => '?',
            'App\\Controller\\PromotionController::ajout' => '?',
            'App\\Controller\\PromotionController::liste' => '?',
            'App\\Controller\\PromotionController::modifier' => '?',
            'App\\Controller\\PromotionController::supprimer' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ProduitController:ajout' => '?',
            'App\\Controller\\ProduitController:liste' => '?',
            'App\\Controller\\ProduitController:modifier' => '?',
            'App\\Controller\\ProduitController:supprimer' => '?',
            'App\\Controller\\PromotionController:ajout' => '?',
            'App\\Controller\\PromotionController:liste' => '?',
            'App\\Controller\\PromotionController:modifier' => '?',
            'App\\Controller\\PromotionController:supprimer' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
