<?php

namespace ContainerMS90gV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2B_AeHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2B.aeH_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2B.aeH_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'materiaux' => ['privates', '.errored..service_locator.2B.aeH_.App\\Entity\\Materiaux', NULL, 'Cannot autowire service ".service_locator.2B.aeH_": it needs an instance of "App\\Entity\\Materiaux" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'materiaux' => 'App\\Entity\\Materiaux',
        ]);
    }
}
