<?php

namespace ContainerMS90gV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7unbaIaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7unbaIa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7unbaIa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'materiauxRepository' => ['privates', 'App\\Repository\\MateriauxRepository', 'getMateriauxRepositoryService', true],
        ], [
            'materiauxRepository' => 'App\\Repository\\MateriauxRepository',
        ]);
    }
}
