<?php

namespace ContainerMS90gV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y4xoLdbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y4xoLdb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y4xoLdb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'atelierenligneRepository' => ['privates', 'App\\Repository\\AtelierenligneRepository', 'getAtelierenligneRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'atelierenligneRepository' => 'App\\Repository\\AtelierenligneRepository',
            'security' => '?',
        ]);
    }
}
