<?php

namespace ContainerMS90gV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAtelierenligneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.c6caRhl.App\Entity\Atelierenligne' shared service.
     *
     * @return \App\Entity\Atelierenligne
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.c6caRhl": it needs an instance of "App\\Entity\\Atelierenligne" but this type has been excluded in "config/services.yaml".');
    }
}
