<?php

namespace ContainerMS90gV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInscriptionatelierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kRfs1Sl.App\Entity\Inscriptionatelier' shared service.
     *
     * @return \App\Entity\Inscriptionatelier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kRfs1Sl": it needs an instance of "App\\Entity\\Inscriptionatelier" but this type has been excluded in "config/services.yaml".');
    }
}
