<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQaxzoOb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQaxzoOb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQaxzoOb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQaxzoOb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQaxzoOb\App_KernelDevDebugContainer([
    'container.build_hash' => 'QaxzoOb',
    'container.build_id' => 'a00a9e88',
    'container.build_time' => 1739131346,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQaxzoOb');
