<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMS90gV3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMS90gV3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMS90gV3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMS90gV3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMS90gV3\App_KernelDevDebugContainer([
    'container.build_hash' => 'MS90gV3',
    'container.build_id' => 'cf5128a5',
    'container.build_time' => 1739746154,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMS90gV3');
