<?php

namespace ContainerDv0FPQ1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N80rZejService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N80rZej' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N80rZej'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ligne' => ['privates', '.errored..service_locator.N80rZej.App\\Entity\\Lignedecommande', NULL, 'Cannot autowire service ".service_locator.N80rZej": it needs an instance of "App\\Entity\\Lignedecommande" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'ligne' => 'App\\Entity\\Lignedecommande',
        ]);
    }
}
