<?php

namespace ContainerDv0FPQ1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RrAsNotService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rrAsNot' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rrAsNot'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paymentService' => ['privates', 'App\\Service\\PaymentService', 'getPaymentServiceService', true],
        ], [
            'paymentService' => 'App\\Service\\PaymentService',
        ]);
    }
}
