<?php

namespace ContainerDv0FPQ1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NmckveXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NmckveX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NmckveX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lignedecommandeRepository' => ['privates', 'App\\Repository\\LignedecommandeRepository', 'getLignedecommandeRepositoryService', true],
        ], [
            'lignedecommandeRepository' => 'App\\Repository\\LignedecommandeRepository',
        ]);
    }
}
