<?php

namespace ContainerDv0FPQ1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLignedecommande3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.N80rZej.App\Entity\Lignedecommande' shared service.
     *
     * @return \App\Entity\Lignedecommande
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.N80rZej": it needs an instance of "App\\Entity\\Lignedecommande" but this type has been excluded in "config/services.yaml".');
    }
}
