<?php

namespace ContainerDv0FPQ1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PaymentService' shared autowired service.
     *
     * @return \App\Service\PaymentService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PaymentService.php';

        return $container->privates['App\\Service\\PaymentService'] = new \App\Service\PaymentService();
    }
}
